### PR TITLE
Added rendering for the patterns in flower forests

### PR DESCRIPTION
**Pull request by OroArmor**
It needs more translations, but otherwise it should be fine

### CODE REVIEW

**Comment by irtimaled** [comment]
What is the PR? Can you share the motivation, and any screenshots of the result.

Since this mod supports 1.14.2 onward how easy would it be to make this PR for master branch?

**Comment by OroArmor** [comment]
Sure. I was thinking of some mod ideas to give myself some practice and tried to make this separately. I had issue rendering, so I forked and worked off of this mod. The reason it's only for fabric 1.16 is that this is what I have modded on, but thinking about the code, there should be no issues porting it to the master branch. I don't have any great images but here are a couple.

**Comment by irtimaled** [comment]
I like the feature but I'm going to rework it a bit. will add you to the contributors file.

**Comment by irtimaled** [comment]
Reworked and included in master... will be released in 2.4

https://github.com/irtimaled/BoundingBoxOutlineReloaded/commit/e378c5a9697a7dd4dcd389d8dcb1696117bfd521

**Comment by OroArmor** [comment]
Thank you so much!

**Pull request closed without merging**
